### ISSUE TITLE
To filter out while discover the entire WLS domain

### ISSUE THREAD

**Issue by VenugopalKake** [oracle/weblogic-deploy-tooling#1001]
Hi Team,
We are migrating applications from On-Premise to OCI, applications deployed on WLS.
For migration of these applications, we are using WDT.
The challenge we are facing is that from source WLS we see many applications and related resources(like JDBC details etc.,) that we don't want to migrate for now.
Is there any way we can filter the discover domain to get only what we need.
Could you please help with this.

Thanks

**Comment by ddsharpe** [comment]
There are two  built-in options for filtering objects: [model filters](https://oracle.github.io/weblogic-deploy-tooling/userguide/tools-config/model_filters/) and [typedefs](https://oracle.github.io/weblogic-deploy-tooling/userguide/tools-config/domain_def/).
Domain typedefs are used to filter applications and other resources during `discoverDomain`.  The intent of the typedef was to counter the WebLogic domain template.  Since you know that the object will be deployed again using the WLS domain template, there is no need to put that object in the model during discovery.  The model filter allows any custom configuration to be done during create, deploy, or discover.  The model filter is a plugin framework where you can write custom Jython/WLST code to manipulate the model.  For example, you can create a method that runs during WDT discoverDomain to inject or remove objects, change attribute values, etc. before WDT writes the discovered model to a file. Create a python file with the filter_model method (see Doc link above), and use the model_filters.json file to inject that .py file into the create similar to `fix-password` in the documentation example.

The example in the doc injects the NodeManager credential every time:
```def filter_model(model):
   if model and 'topology' in model:
       if 'SecurityConfiguration' in model['topology']:
           model['topology']['SecurityConfiguration']['CredentialEncrypted'] = 'welcome1'
           model['topology']['SecurityConfiguration']['NodeManagerPasswordEncrypted'] = 'welcome1'
           print 'Replaced SecurityConfiguration password'
       else:
           print 'SecurityConfiguration not in the model'
```
