### ISSUE TITLE
Discovery tool doesn't include default parameter values in model result

### ISSUE THREAD

**Issue by rssh22** [oracle/weblogic-deploy-tooling#1044]
```
 "JMSServer": {
            "hcdsns-be-jee-r02a-id-c04-m1-n1-jmss": {
                "BytesMaximum": 1500000000,
                "MaximumMessageSize": 400000000,
                "PersistentStore": "hcdsns-be-jee-r02a-id-c04-m1-n1-fst",
                "Target": "hcdsns-be-jee-r02a-id-c04-m1-n1 (migratable)"
            },
```

I don't know if this is a bug. If it is working as expected, could a RFE be opened so default parameter values be included in the model? (it would be easier to modify the model later if all parameters were included by the tool)

**Comment by CarolynRountree** [comment]
This is as designed. The model is a sparse model, thus we don't include attributes that are set to the default value.

**Comment by robertpatrick** [comment]
@rssh22 as Carolyn has said, this is by design.  If we did what you are suggesting, the discovered model would be thousands of lines long... (e.g., each Server has over 300 attributes alone).  We opted for not including parameters set to their default values because we felt like the usability of the model would be significantly reduced by giving you a thousand line model file where you had no idea which parameters were customized and which were simply default settings.

Try using `modelHelp.sh` to see what the parameter names and subfolders are.
