### ISSUE TITLE
Using custom AuthenticationProvider and custom CredentialMapper

### ISSUE THREAD

**Issue by d-bechtel** [oracle/weblogic-deploy-tooling#164]
Hi,

we are using a custom AuthenticationProvider (IdentityAsserter) and a custom CredentialMapper. 
Is it possible to create them with WDT?

In WLST we use:
`cd( _Realm_cd_cmo )
  cmo.createAuthenticationProvider( "CustomIdentityAsserter", "my.package.weblogic.CustomIdentityAsserter" )
  cd( _Realm_cd_cmo + "/AuthenticationProviders/CustomIdentityAsserter" )
  set( "ControlFlag", "SUFFICIENT" )  `

and:
`cd( _Realm_cd_cmo )
  cmo.createCredentialMapper('CustomCredentialMapper', 'my.package.CustomCredentialMapper')`

**Comment by CarolynRountree** [comment]
We do deploy,update the realm information. Below is a simple yaml example. You can use the discover tool against a configured domain to prime a yaml / json file. If you want to create it by hand, this section follows the "three" names that are needed to create a provider MBean. First level is the type of Provider (AuthenticationProvider, CredentialMapper), second level is the name of your MBean, and third level is the specific type of Provider (i.e. DefaultIdentityAsserter, PKICredentialMapper), and then the attributes of that provider implementation.

 SecurityConfiguration:
        CredentialEncrypted: '--FIX ME--'
        NodeManagerUsername: UKFwCW1CLs
        Realm:
            myrealm:
                AuthenticationProvider:
                    My Identity Asserter:
						DefaultIdentityAsserter:
							UserNameMapperClassName: mymapper
				CredentialMapper:
					mymapper:
						DefaultCredentialMapper:
							CredentialMappingDeploymentEnabled: true

**Comment by d-bechtel** [comment]
My model looks like:
          "{
    myrealm": {
                    "AuthenticationProvider": {
                        "DefaultAuthenticator": {
                            "DefaultAuthenticator": {
                                "ControlFlag": "OPTIONAL"
                            }
                        },  
                        "My custom IdentityAsserter": {
                            "CustomIdentityAsserter": {
                                "UserNameMapperClassName": "my.package.CustomIdentityAsserter",
                                "ControlFlag": "SUFFICIENT"
                            }
                        }
                    },
                    "CredentialMapper": {
                        "My custom CredentialMapper": {
                            "CustomCredentialMapperProvider": {
                                "UserNameMapperClassName": "my.package.CustomCredentialMapper",
                                "CredentialMappingDeploymentEnabled": true
                            }
                        }
                    }
                }
}

And my MBean for the Identity Asserter :
<MBeanType
        Name          = "CustomIdentityAsserter"
        DisplayName   = "CustomIdentityAsserter"
        Package       = "my.package"
        Extends       = "weblogic.management.security.authentication.IdentityAsserter"
        PersistPolicy = "OnUpdate"
>

On validation the model, i get the error:
CustomIdentityAsserter is not one of the folder names allowed in model location topology:/SecurityConfiguration/domain/Realm/myrealm/AuthenticationProvider/My custom IdentityAsserter

**Comment by CarolynRountree** [comment]
Currently we only support the weblogic delivered Authentication provider types. I'm sorry, I did not look to see if CustomIdentityAsserter was one of the provider types. It is not one of the delivered types. The tool would need to be enhanced to support custom providers. Could you provide us with more information about your custom asserter and its attributes? Also, if you could include whether the class overrides another asserter and if so, if it extends the attributes of that asserter.

**Comment by CarolynRountree** [comment]
Please send information about your custom credential mapper too - name and attributes.

**Comment by d-bechtel** [comment]
i have uploaded the mbean definition files for the identity asserter and credential mapper.

[identity-asster-mdf.txt](https://github.com/oracle/weblogic-deploy-tooling/files/2399878/identity-asster-mdf.txt)
[credential-mapper-mdf.txt](https://github.com/oracle/weblogic-deploy-tooling/files/2399879/credential-mapper-mdf.txt)

**Comment by ddsharpe** [comment]
Custom identity asserters has not been implemented yet.  But, I think we should add this to the priority list and support them in the next release.

**Comment by CarolynRountree** [comment]
BrianLet me talk with my manager Derek Sharpe. We have been talking about, it is on our priority list, fir one if the upcoming sprints. Do you have a timeline?Also, what is your goal? Are you planning to create an image with the custom security provider so that when you start a server container with the image, no changes ?Carolyn Rountree On Jan 24, 2019 11:37 AM, Bryan Tidd <notifications@github.com> wrote:What is the status of this issue? We have the requirement to use a custom authentication provider defined in a third party jar (OpenAM). Our current method via WLST is similar to that listed above by the issue creator:
`cd('/SecurityConfiguration/'+domain_name+'/Realms/myrealm')
In the following command, substitute the appropriate class type
cmo.createAuthenticationProvider('AgentAuthenticator','com.sun.identity.agents.weblogic.v10.AgentAuthenticator')
cd('/SecurityConfiguration/'+domain_name+'/Realms/myrealm/AuthenticationProviders/AgentAuthenticator')
cmo.setControlFlag('OPTIONAL')
cd('/SecurityConfiguration/'+domain_name+'/Realms/myrealm')
set('AuthenticationProviders',jarray.array([ObjectName('Security:Name=myrealmAgentAuthenticator'), ObjectName('Security:Name=myrealmDefaultAuthenticator'), ObjectName('Security:Name=myrealmDefaultIdentityAsserter')], ObjectName))
`
Since this is a non-dynamic change, it requires a restart of the wls server. This is quite sub-optimal in a kubernetes environment while using the weblogic-kubernetes-operator.
Thank you

**Comment by ddsharpe** [comment]
@bryantidd I agree that this would be a valuable addition to the tool.  We intend to start working on this use case on Monday.  The ETA is probably 2-3 weeks from today.

**Comment by bryantidd** [comment]
Please let me know If I can be a tester for this, etc. It's critical path in my case. Motivated to be helpful.

**Comment by opncow** [comment]
Any news on this? Having an eye on this issue as it is also important for us right now.

**Comment by ddsharpe** [comment]
We are actively working this enhancement.  Unless we hit a major showstopper, this feature should be available in the next release (within the next week).
