### ISSUE TITLE
discover.py hangs when logging.properties file is not found

### ISSUE THREAD

**Issue by hbozic** [oracle/weblogic-deploy-tooling#204]
PS C:\Users\me\temp\weblogic-deploy\bin> .\discoverDomain.cmd  -oracle_home D:\Oracle\WLS\ -domain_home D:\Oracle\user_projects\domains\DEV4\   -archive_file C:\Users\me\temp\archde
v7
JDK version is 1.8.0_162, setting JAVA_VENDOR to Sun...
WLSDEPLOY_HOME = D:\Oracle\user_projects\domains\DEV4
TESTFILES_PATH =
JAVA_HOME = D:\Java\jdk1.8.0_162
WLST_EXT_CLASSPATH = D:\Oracle\user_projects\domains\DEV4\lib\weblogic-deploy-core.jar
CLASSPATH =
WLST_PROPERTIES = -Djava.util.logging.config.class=oracle.weblogic.deploy.logging.WLSDeployCustomizeLoggingConfig -Dcom.oracle.cie.script.throwException=true
D:\Oracle\WLS\\oracle_common\common\bin\wlst.cmd "D:\Oracle\user_projects\domains\DEV4\lib\python\discover.py" -oracle_home D:\Oracle\WLS\ -domain_home D:\Oracle\user_projects\domains\DEV4\ -archive_file C:\Users\me\temp\archdev7
Unable to find D:\Oracle\user_projects\domains\DEV4\etc\logging.properties file so skipping logging configuration
(hangs at this point)

----------------------------------------------------------------------------
placing the logging.properties in the subdirectory allows the script to complete.

**Comment by CarolynRountree** [comment]
This is related to a problem in the java LogManager class.
1. The LogManager sets up a shutdown hook to clean up the loggers on exit. 
2. The LogManager creates a lock on itself (the only LogManager in the system) in a synchronized call. Within the synchronized, It calls the constructor of the class on the argument -Djava.util.logging.config.class
3. This class is our log configurator WLSDeployLoggingConfig. This class constructor determines that the logging.properties is not valid and performs a System.exit(2) expecting the cmd / sh script to print a nice clean message about the RC=2
4. The System.exit calls all the application shutdown hooks.
r. The  LogManager shutdown hook (see step 1) creates a lock on itself (the only LogManager in the system) to set some global variables. This call blocks forever because now we have a deadlock.

To address this issue, we need to do the following:

1. All of our cmd | sh scripts need to document that the following two environment variables overrides the default locations:
- WLSDEPLOY_LOG_PROPERTIES to override the location and name of the logging properties file
- WLSDEPLOY_LOG_DIRECTORY to override the directory where the logs are stored.

2. Work around the described LogManager problem by replacing all the System.exit() calls in the logger configuration class. Additionally, each "exit" should not only print information to stderr about the problem but also, if pertinent, direct the user to an override environment variable
