### ISSUE TITLE
DiscoverDomain issue when using slash as part of workManager name

### ISSUE THREAD

**Issue by MarinaLevin** [oracle/weblogic-deploy-tooling#308]
We have a problem  while  running discoverDomain util on WorkManger  named wm/omsThreadPool :
 WLSDPLY-06140: Unable to cd to the expected path /SelfTuning/OmsDomain/WorkManager/wm/omsThreadPool constructed from location context model_folders = ['SelfTuning', 'WorkManager'],  'name_tokens' = {'SELFTUNING': 'OmsDomain','DOMAIN': 'OmsDomain','WORKMANAGER': 'wm/omsThreadPool'}; the current folder and its sub-folders cannot be discovered : wlst.cd(/SelfTuning/OmsDomain/WorkManager/wm/omsThreadPool) in offline mode failed: com.oracle.cie.domain.script.ScriptException: No such element WorkManager named wm

**Comment by ddsharpe** [comment]
@MarinaLevin This is a WLST issue that was patched in 2017 for 12.2.1.2.  The issue was that the slash in the name was treated as a directory by WLST offline.  You can try to access the patch through your MOS account or OTN, or you can file a support ticket with Oracle Support if the patch is not available for your version of WLS yet.  I recommend referencing the bug number posted by jshum2479 to speed up the search, bug 25790276.
