### ISSUE TITLE
Alias change needed for Partition PartitionWorkManager

### ISSUE THREAD

**Issue by CarolynRountree** [oracle/weblogic-deploy-tooling#38]
Partition.json includes the PartitionWorkManager.json file. However, the wlst_type for PartitionWorkManager is PartitionWorkManager${:s}. This is correct for the global mbean in online wlst - it is /PartitionWorkManagers. For Partitions it is /Partitions/PartitionWorkManager. Remove the include for PartitionWorkManager in Partition.json and add the PartitionWorkManager folder with the correct wlst_type.

**Comment by mwooten** [comment]
Hi Carolyn,

I'm ready to do the proposed change, but I want to double check that I'm reading this correctly. You're saying the issue here is that right now, /Partitions/PartitionWorkManager**s** is being returned in wlst online mode - but it should be /Partitions/PartitionWorkManager. 

The proposed fix is to:

1. Give Partition.json it's own PartitionWorkManager folder (by copying from PartitionWorkManager.json), and give the copy a "wlst_type": "PartitionWorkManager" (not_ "wlst_type": "PartitionWorkManager**${:s}**") field.
2. Remove "PartitionWorkManager" from the "contains" list, in Partition.json.
3. Leave the PartitionWorkManager.json, as it is.

Correct?

**Comment by CarolynRountree** [comment]
Correct.

**Comment by CarolynRountree** [comment]
Don't forget to change the wlst_path. Test to make sure that's all that needs to be changed.

**Comment by mwooten** [comment]
...I didn't forget :-)

    "wlst_paths": {
        "WP001": "/Partition${:s}/%PARTITION%/PartitionWorkManager/%PARTITIONWM%"
    }

Will definitely test it, before I push the changes.
