### ISSUE TITLE
Unexpected exception occurred adding File Store mds-owsm directory store/gmds to archive file>

### ISSUE THREAD

**Issue by atjapan2015** [oracle/weblogic-deploy-tooling#472]
Hi Experts,

This is an error occurred while trying to discovery domain on JCS(Oracle Java Cloud Service).

I'm working on migrating JCS(Oracle Java Cloud Service) to Oracle Weblogic Cloud on OCI(Oracle Cloud Infrastructure).
Big background is to help customer to move existing JCS to OCI easily.

Firstly, I tried to install Weblogic on one Virtual Machine, and had discovered the domain successfully.
Secondly, I tried to discovery the domain of on JCS, it failed with error [Unexpected exception occurred adding File Store mds-owsm directory store/gmds to archive file] .

[Detailed Information]
1, JCS version is 12.2.1.3.190815
2, Deploy Tooling version is 1.5.0
3, Error logs: Attached file
[20191030_errorlogs.txt](https://github.com/oracle/weblogic-deploy-tooling/files/3786604/20191030_errorlogs.txt)

[Questiong]
1, Does deploy tooling support JCS(Oracle Java Cloud Service)? 
1-1, If the answer is Yes, could you please tell us how to solve the error?
1-2, If the answer is No, do you have any plan to support JCS in the future?

Thanks in advance!

**Comment by ddsharpe** [comment]
I do not have access to JCS, so I am unable to test in that environment.  But, the JCS team reports that they have tested this discovery without any issues.  Looking at the WDT log, the failure is due to the zip command failing to store the mds-owsm file store directory store/gmds.  Is that directory available on the machine where you are running WDT?  If that directory is on a remote machine, you can copy it over to the local file system, or just create an empty directory temporarily to allow WDT to complete (depending on if you need the contents or not).

**Comment by atjapan2015** [comment]
Hi ddsharpe,

Thanks for your quick response!

Based on your answer, I checked whether the folder is exist, there is a folder (/u01/data/domains/jcstesti_domain/store/gmds) there without no file, and I have permission with user "oracle".

At last, I figured out that I forgot to make a folder(named data) at where I run discoverDomain.sh because I wanted to output yaml&zip file to "data" folder.
`bin/discoverDomain.sh -oracle_home /u01/app/oracle/middleware -domain_home /u01/data/domains/jcstesti_domain -archive_file data/jcstesti_domain.zip -model_file data/jcstesti_domain.yaml`

The error message is a little undirectly so I was not aware of that before your answer.
Please close this issue/question.

Thanks!

**Comment by ddsharpe** [comment]
Thank you @atjapan2015 .  I have opened a new issue  to improve the error message.  See #474
