### ISSUE TITLE
Template versions

### ISSUE THREAD

**Issue by kaifricke** [oracle/weblogic-deploy-tooling#487]
Hello,

I have a custom definition for Fusion Middleware 12.2.1.3.0. Now I want to do the same for 12.2.1.4.0.
I realised that the version of the domain templates, for example the "Base Weblogic Server Domain", is in 12.2.1.4.0  version 12.2.1.3.0 (same as in 12.2.1.3.0).  Is that by intention or is that a bug. 

-Kai

**Comment by ddsharpe** [comment]
That is intentional.  The installation framework changed the method of selecting the underlying domain templates to this "named" approach.  Since there can be only one domain template with that name per Oracle Home, the name is now the same across versions (starting with 12.2.1) and is selected by your choice of Oracle Home.
