### ISSUE TITLE
Definition from typedef for OSB

### ISSUE THREAD

**Issue by ashok11gai** [oracle/weblogic-deploy-tooling#520]
Hi ,
I'm creating a OSB 12.2.1.4 domain with below type def. 
Can anyone validate if this is suported and proper typedef for OSB.

        "JRF_12CR2": {
            "baseTemplate": "Basic WebLogic Server Domain",
            "extensionTemplates": [
                "Oracle JRF WebServices Asynchronous services",
                "Oracle Service Bus Reference Configuration"
            ],
            "customExtensionTemplates": [ ],
            "serverGroupsToTarget": [ "JRF-MAN-SVR", "OSB-MGD-SVRS-COMBINED" ],
            "rcuSchemas": [ "MDS", "IAU", "IAU_VIEWER", "IAU_APPEND", "OPSS", "STB", "SOAINFRA", "WLS" ]
        }
    }
}
Thanks,

**Comment by ddsharpe** [comment]
@ashok11gai I don't think anyone from OSB is monitoring this channel.  I assume that you modified JRF just as a quick test.  Normally, you would create a new typedef for the install that you are trying, such as OSB.json and mimic what is in the JRF.json.  Then, you can use the selector from the tools to create or discover OSB domains.  Otherwise , it looks correct, but I don't know OSB installation requirements.  Sorry I cannot be more help.  I would ask that you try to reach out to Oracle Support or Oracle development team on OSB or SOA.
