### ISSUE TITLE
Question about OBIEE

### ISSUE THREAD

**Issue by textanalyticsman** [oracle/weblogic-deploy-tooling#560]
I have a short question, could I use this Weblogic deploy tooling to perform the following tasks?

1. Introspect an OBIEE 12.2.1.4 domain.
2. Change the configuration on the file generated by Weblogic deploy tooling.
3. Deploy a new OBIEE domain.

**Comment by ddsharpe** [comment]
The BI install is not described in the WDT typedefs.  Because WDT does not know what the domain templates are, it doesn't know the difference between Oracle product deployments and user deployed applications/configurations.  You should be able teach WDT to understand BI, but it is not programmed to do so today.
