### ISSUE TITLE
seeking example of using domain encrypted passwords in yaml model

### ISSUE THREAD

**Issue by gthomas01** [oracle/weblogic-deploy-tooling#740]
I see that using domain encrypted passwords is an option in the model but I'm not seeing any further example or explanations.

                JDBCDriverParams:
                    URL: 'jdbc:oracle:thin:@url.com'
                    PasswordEncrypted: '--FIX ME--'
                    DriverName: oracle.jdbc.OracleDriver
 

In our home grown python process our developers pre-encrypt the passwords and store them in a user/keyfile setup.  Then we apply 
 setEncrypted('/JDBCSystemResources/poolname/JDBCResource/poolname/JDBCDriverParams/poolname/Password','user_alias', './userlist.txt', './key_file.txt')

We have some concerns about the model encryption.  Keeping the passphrase standardized and consistent for the life of the configuration could prove challenging since its not included in the model/archive.   This would be true for larger development teams.

**Comment by rakillen** [comment]
hi gthomas01 -

You can use domain-encrypted passwords directly in the model, and those will be applied to the target domain. For example:
```
                PasswordEncrypted: '{AES}xxxx'
```
or, better yet, store them in a separate (secure) properties file, and reference as:
```
                PasswordEncrypted: '@@PROP:mypwd@@'
```
This is not very common, since it can't be used when creating a domain (the passwords can't be derived yet). It could be useful in an update / deploy operation, though.

Domain-encrypted passwords can't be used in tandem with model encryption, but it looks like you aren't using that.

**Comment by gthomas01** [comment]
Thank you!  that is what I was looking for.
