### ISSUE TITLE
Discovery domain(12.1.3.0) offline -  WLSDPLY-06140: Unable to cd to the expected path

### ISSUE THREAD

**Issue by prathapdasari** [oracle/weblogic-deploy-tooling#803]
Hie ,

I am trying to discover a domain(12.1.3.0) online and I am getting errors detailed below.

I am using this command.

C:\Users\e_prd\Downloads\weblogic-deploy\weblogic-deploy\discoverDomain.cmd -oracle_home D:\u01\app\Middleware\Oracle_Home -domain_home D:\u01\config\domains\soa_domain -archive_file C:\Users\e_prd\Downloads\DiscoveredOSBDomain.zip  -model_file C:\Users\e_prd\Downloads\DiscoveredOSBDomain.yaml 

29. WLSDPLY-06140: Unable to cd to the expected path /JMSSystemResource/U
MSJMSSystemResource/JmsResource/NO_NAME_0/UniformDistributedQueue/dist_OraSDPM/Q
ueues/OraSDPMWSRcvQ1_auto constructed from location context model_folders = ['JM
SSystemResource', 'JmsResource', 'UniformDistributedQueue'],  'name_tokens' = {'
UNIFORMDISTRIBUTEDQUEUE': 'dist_OraSDPM/Queues/OraSDPMWSRcvQ1_auto','JMSRESOURCE
': 'NO_NAME_0','DOMAIN': 'soa_domain','JMSSYSTEMRESOURCE': 'UMSJMSSystemResource
'}; the current folder and its sub-folders cannot be discovered : cd(/JMSSystemR
esource/UMSJMSSystemResource/JmsResource/NO_NAME_0/UniformDistributedQueue/dist_
OraSDPM/Queues/OraSDPMWSRcvQ1_auto) in offline mode failed: java.lang.Unsupporte
dOperationException: Could not create generic operation:Queue

**Comment by ddsharpe** [comment]
Unfortunately, WLST 12.1.3 (WebLogic Scripting Tool) has known issues with the slash (/) in object names.  We looked into coding around these issues in WDT but the workaround that is required would only apply to WLS 12.1.x because the workaround breaks in 12.2.1.x (the next version of WebLogic Server).  We, also, found that the WebLogic documentation for 12.1.3 recommends that slashes not be used in object names at all.

We do not have plans to implement a workaround for slashes in the object names for WLS 12.1.x.  But, the slashes in the names for version 12.2.1.x domains should work.

**Comment by ddsharpe** [comment]
Won't fix for 12.1.3 and earlier.
