### ISSUE TITLE
OAM Identity Asserter

### ISSUE THREAD

**Issue by jlirette1** [oracle/weblogic-deploy-tooling#836]
There does not appear to be any support for the OAMIdentityAsserter Provider in the Weblogic-deploy-tooling. Is this something that is able to be added in to allow for the asserter to be created. When adding the jar and provider by hand and then using the Discover tool it does generate a model with it listed however it will not build the provider when redeploying.

**Comment by CarolynRountree** [comment]
In order to create a security provider using offline WLST, you must not only have the provider installed into the MBean directory, but you must also create a schema jar. This schema jar allows offline WLST to understand the MBean structure of the custom security provider. Check the section on Custom Security Providers here:
https://github.com/oracle/weblogic-deploy-tooling/blob/master/site/use_cases.md#modeling-security-providers

**Comment by ddsharpe** [comment]
Closing due to lack of response.
