### ISSUE TITLE
ResourceGroupTemplates removal failure

### ISSUE THREAD

**Issue by pwninja** [oracle/weblogic-deploy-tooling#853]
Hi!
When I am trying to install a domain including Oracle Service Bus I am facing an issue while trying to remove ResourceGroupTemplates:

```
    ####<Mar 12, 2021 1:57:39 PM> <INFO> <deployer_utils> <delete_named_element> <WLSDPLY-09110> <Deleting ResourceGroupTemplate OSBAdminSvrOnlyResourceGroupTemplate>

    Issue Log for createDomain version 1.9.8 running WebLogic version 12.2.1.4.0 offline mode:

    SEVERE Messages:

            1. WLSDPLY-12409: createDomain failed to create the domain: updateDomain() failed : Error updating domain:
    null
     @org.apache.xmlbeans.impl.values.XmlObjectBase.check_orphaned(XmlObjectBase.java:1268)
```

Same happens no matter if I attempt to remove one or all ResourceGroupTemplates.

```
resources:
    ResourceGroupTemplate:
        '!OSBAdminSvrOnlyResourceGroupTemplate':
```

When running from WLST before I actually delete RGT I have to remove the references:
`editService.getConfigurationManager().removeReferencesToBean(getMBean('/ResourceGroupTemplates/OSBAdminSvrOnlyResourceGroupTemplate'))`
How to achieve it in WDT?

Why I am doing that is because of the recommendation from Oracle due to slow loading of Deployments tab.

**Comment by ddsharpe** [comment]
@pwninja How was the domain created and configured?  WDT does not officially support SOA and OSB, yet.  But, I can try to take a look at this scenario for you if you help me recreate a similar domain that I can look at.

**Comment by pwninja** [comment]
@ddsharpe Thanks for your swift reply! I'd need to prepare some simplified model without all our dependencies to provide here.
However, I am a bit surprised - isn't the Oracle Service Bus on K8s based on WDT and certified for production already? How come it is not supported then?

**Comment by textanalyticsman** [comment]
@ddsharpe I have been working with WDT on SOA/OSB domains for a while now and I have understood WDT does not support really specific SOA/OSB configurations i.e. application roles, importing policies, etc., which makes sense as WDT is about Weblogic. 

However, this one looks like something that should be supported by WDT as it is about managing resource group templates. Thus, my question would be is WDT able to delete resource group templates?

@rakillen perhaps you can have another point of view on this?

**Comment by ddsharpe** [comment]
@textanalyticsman Yes, WDT should be able to delete resource group templates.  That was not my question.  My question that I sent to SOA development was about deleting that specific template, and was this a recommended practice.  The development team responded in the affirmative.  I am trying to get a copy of their domain template so that I can figure out the dependencies that are preventing the deletion during @pwninja run.

**Comment by textanalyticsman** [comment]
Thanks a lot @ddsharpe

**Comment by ddsharpe** [comment]
From what I can tell, WLST removes the references to anything that I have tried to delete with the exception of ResourceGroupTemplate types.  I am pursuing this as a WLST bug, but we may need a workaround in WDT.

**Comment by ddsharpe** [comment]
@pwninja After further investigation, I believe that I was mistaken regarding the WLST bug.  WLST does not cascade deletions for  targetable resources.  Unfortunately, there does not appear to be an easy way to to implement this in WDT.  The function removeReferencesToBean() in only available online and there is no offline WLST option.  If SOA/OSB does not recommend these ResourceGroupTemplates in the domain, then those objects should be removed from the domain template by a patch or PSU.  In order to remove an RGT using WDT, you will need to delete all of the reference to the ResourceGroupTemplate along with the ResourceGroupTemplate itself in the same model.  You should be able to use discoverDomain.sh to locate them and create a starting point for trying to delete them.

**Comment by ddsharpe** [comment]
Per https://github.com/oracle/weblogic-deploy-tooling/issues/919#issuecomment-866638267, I am closing this issue.  Please reopen if I misunderstand this as resolved.
