### ISSUE TITLE
Deploy application specific config

### ISSUE THREAD

**Issue by belfo** [oracle/weblogic-deploy-tooling#944]
Hello,

i'm looking how to deploy specific application configuration, like xml config file or properties files, as part of the archive model file
Even better if we could use some template in this files that will be replaced once the application is started

If it's not possible with the WDT, what would be a better option?

Regards

**Comment by CarolynRountree** [comment]
If we enhanced to create a folder in which you could store what you want and WDT would unzip the contents into the location in the domain, would that satisfy your needs?

**Comment by belfo** [comment]
Yes this would be perfect.

**Comment by belfo** [comment]
Would also be needed to be able to deploy mbeantypes and schematype to be able to deploy a custom security provider
https://oracle.github.io/weblogic-deploy-tooling/samples/securityproviders-model/#custom-security-providers

**Comment by CarolynRountree** [comment]
You might consider using Weblogic Image Tool. It can help you run WDT inside a dockeer container, it has several touchpoints where you can perform actions such as moving mbeantype and schematype jars into the correct location. If you are interested in creating your domain in docker image, or your model in docker image. 
Otherwise, we can discuss unzip archive first so that you can write a filter to move the files into position.

https://github.com/oracle/weblogic-image-tool

**Comment by belfo** [comment]
yes for the moment i'm using the Image tool, but still i need to run the security part online. Not sure why the "offline" don't work.
